### ISSUE TITLE
importing mcpi with python3 does not work

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/getting-started-with-minecraft-pi#14]
The worksheet instructs to use the Python3 menu item, which invokes IDLE3, which in turn invokes the python3.2.3 interpreter

The first step, to import minecraft from the mcpi module, then fails:
pi@RPi2B ~ $ python3
Python 3.2.3 (default, Mar  1 2013, 11:53:50)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcpi import minecraft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mcpi
>>>

It imports correctly using the Python/IDLE/python2.7.3 option. The sample screenshot in the worksheet was generated using python2.7.3

See this thread in the Raspberry Pi forums for an example of how confusing this can be: https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=115897&p=796407#p790089

**Comment by bennuttall** [comment]
We added Python 3 support a couple of months ago. Run

```bash
sudo apt-get update
sudo apt-get upgrade
```

and you'll have the Python 3 version too.

**Comment by san560** [comment]
exscuse me but i have a  problem with the import mcpi command on python 2.7.3 here lemme post you the error i got and the code i used
![screenshot 8](https://user-images.githubusercontent.com/30332496/28447650-fcb62cde-6d86-11e7-8fa0-e5cfab032701.png)

![screenshot 9](https://user-images.githubusercontent.com/30332496/28447662-11b93932-6d87-11e7-8ac6-82fa55b7b270.png)

on the error, screenshot look at the bottom one
it said target actively refused it is it something with my firewall or computer or something

**Comment by san560** [comment]
if you want anything more from me just ask

**Comment by bennuttall** [comment]
You're using Windows but Minecraft Pi is only available for Raspberry Pi.

**Comment by san560** [comment]
Bennutal is there any way for python to think that im using rasbeery pi even though i am not cuase i swear there is a way to use that same command without the rasbeery pi

**Comment by beiop** [comment]
the problem is that you cant get MCPI on windows

**Comment by PythonScratcher** [comment]
> the problem is that you cant get MCPI on windows

wsl
