### ISSUE TITLE
Project site feedback (Jul 2019)

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/getting-started-with-minecraft-pi#29]
URL: /en/projects/getting-started-with-minecraft-pi Minecraft Pi takes over my Pi 4's screen, and pressing Tab does nothing. I can't find any good way to quit the program without simply cutting the power to the Pi. These instructions need to be updated to indicate how exactly to quit the program

**Comment by libxx1** [comment]
On latest o/s on pi 4 when going full screen the minecraft titlebar remains at the top with option to minimise. Closing as resolved
